-- CREATE A TABLE IN AN SPECIFIC DATABASE
-- DATABASE PASSED AS AN ARGUMENT
-- THE COLUMNS ARE ID, NAME
-- NAME OF TABLE 'FIRST_TABLE'
CREATE TABLE If NOT EXISTS first_table (
	id INT NULL,
	name VARCHAR(256)
) ENGINE=INNODB;
