-- CREATE A DATABASE AND USER
-- GRANT ONLY READ PRIVILEGES FOR USER INTO DATABASE
-- CHECKS IF DATABASE OR USER EXISTS TO CATCH FAILED
-- SET A PASSWORD FOR AN USE
CREATE DATABASE IF NOT EXISTS hbtn_0d_2;
GRANT SELECT ON hbtn_0d_2.* TO 'user_0d_2'@'localhost' IDENTIFIED BY 'user_0d_2_pwd';
